paths:
  input_base: "/data/harippriya/characterisation_github/Input"
  output_base: "/data/harippriya/characterisation_github/Output"
  # Permanent location for antiSMASH databases
  database_dir: "/data/harippriya/characterisation_github/databases/antismash_db"
  # envs
  antismash: "envs/antismash.yaml"
  abricate: "envs/abricate.yaml"

params:
  antismash_threads: 8
  abricate_threads: 40
  abricate_databases: ["ncbi", "card", "vfdb", "bacmet2"]
